version: "3.8"

services:
  bot:
    image: rylorin/meme-trader:dev
    environment:
      KUCOINAPI_AUTH_KEY: ${KUCOINAPI_AUTH_KEY}
      KUCOINAPI_AUTH_SECRET: ${KUCOINAPI_AUTH_SECRET}
      KUCOINAPI_AUTH_PASS: ${KUCOINAPI_AUTH_PASS}
      TELEGRAM_API_KEY: ${TELEGRAM_API_KEY}
    restart: unless-stopped
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == manager
      replicas: 1
    configs:
      - source: meme-trader-local.json
        target: /root/config/local.json
      - source: meme-trader.json_02
        target: /root/config/production.json

networks:
  default:

configs:
  meme-trader.json_02:
    external: true
  meme-trader-local.json:
    external: true
